import '@/app/globals.css'
import { Providers } from '@/app/providers'
import { api } from '@/lib/api'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const refreshToken = async () => {
	const res = await api.get('auth/refresh')
	if (!res.ok) return null
	const { accessToken } = await res.json<{ accessToken: string }>()
	return accessToken
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const accessToken = await refreshToken()

	console.log(accessToken)

	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
