import '@/app/globals.css'
import { Providers } from '@/app/providers'
import { Toaster } from '@/components/ui/toaster'
import { Locale, locales } from '@/lib/config/locales'
import type { Metadata } from 'next'
import { NextIntlClientProvider, createTranslator } from 'next-intl'
import { Inter } from 'next/font/google'
import { notFound } from 'next/navigation'
import { PropsWithChildren } from 'react'

type Params = { params: { locale: Locale } }

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const getMessages = async (locale: Locale) => {
  try {
    return (await import(`i18n/${locale}.json`)).default
  } catch (error) {
    notFound()
  }
}

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

export async function generateMetadata({ params: { locale } }: Params) {
  const messages = await getMessages(locale)
  const t = createTranslator({ locale, messages })
  return { title: t('Layout.title') }
}

const font = Inter({ subsets: ['latin'] })

export default async function RootLayout({
  children,
  params: { locale }
}: PropsWithChildren<Params>) {
  const messages = await getMessages(locale)

  return (
    <html lang={locale}>
      <body className={`${font.className} dark text-foreground bg-background min-h-screen`}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <Toaster />
          <Providers>{children}</Providers>
          {/* <GoogleOneTap /> */}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
